title: Managing merge conflicts
description: Merge conflicts are a normal part of working in Git. Learn why they happen and how to resolve them with ease.
template:
  name: zwift-basics
  repo: zwift-basics-template
preferences:
- type: radio
  name: gitTool
  label: Preferred Git tool
  description: Learn right from the web UI, or using your chosen tool
  options:
    - label: Use the GitHub.com web interface
      value: dotcom
    - label: Use the command line
      value: cli
    - label: Use GitHub Desktop
      value: desktop
tags:
  - Git
  - Merge conflicts
  - GitHub
before:
  - type: updateBranchProtection
  - type: createPullRequest
    title: "Welcome! Let's resolve a conflict"
    body: 00_welcome-conflict-1.md
    head: update-config
    data:
      thePayload: "%payload%"
  - type: createPullRequest
    title: Another User's Change
    body: 00_another-user-conflict-6.md
    head: education-conflict
    action_id: another_users_pr
  - type: createPullRequest
    title: More conflicts
    body: 00_more-conflicts-3.md
    head: add-experience
  - type: createPullRequest
    title: Create your own conflict
    body: 00_create-conflict-5.md
    head: add-education

steps:
  #step 1 - resolve conflict
  - title: Resolve a conflict
    description: Resolve your first merge conflict
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/1"
    actions:
      - type: removeBranchProtection
      - type: getPullRequest
        waitForMergeable: true
        action_id: pr
      - type: gate
        left: "%actions.pr.data.mergeable%"
        else:
          type: respond
          with: e_error.md
      - type: respond
        with: 01_success.md
        data:
          branch: "%payload.pull_request.head.ref%"

  #step 2 - merge
  - title: Merge the first resolved pull request
    description: Merge the pull request that holds your first, simple conflict
    event: pull_request.closed
    link: "{{ repoUrl }}/pull/1"
    actions:
      - type: gate
        left: "%payload.pull_request.head.ref%"
        operator: "==="
        right: update-config
        else:
          type: respond
          with: e_error.md
      - type: getPullRequest
        pullRequest: More conflicts
        action_id: next_pr
      - type: updateBranchProtection
      - type: respond
        with: 02_delete.md
        data:
          url: "%actions.next_pr.data.html_url%"

  #step 3: More complex conflicts
  - title: Resolve conflicts in a more complex pull request
    description: Resolve the merge conflict in a more complex pull request
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/3"
    actions:
      - type: gate
        left: "%payload.pull_request.head.ref%"
        operator: "==="
        right: add-experience
        else:
          type: respond
          with: e_error.md
      - type: getPullRequest
      - type: respond
        with: 03_PR-free-of-conflicts.md
        data:
          branch: "%payload.pull_request.head.ref%"
      - type: removeBranchProtection

  #step 4: merge
  - title: Merge the pull request
    description: Merge the pull request
    event: pull_request.closed
    link: "{{ repoUrl }}/pull/3"
    actions:
      - type: gate
        left: "%payload.pull_request.head.ref%"
        operator: "==="
        right: add-experience
        else:
          type: respond
          with: e_error.md
      - type: gate
        left: "%payload.pull_request.merged%"
      - type: getPullRequest
        pullRequest: Create your own conflict
        action_id: conflict_pr
      - type: respond
        with: 04_next-steps.md
        data:
          url: "%actions.conflict_pr.data.html_url%"
      - type: updateBranchProtection

  #step 5: Create a conflict
  - title: Create your own conflict
    description: Commit changes to the `_data/education.yml` file on the `add-education` branch in the 'Create Your Own Conflict' Pull Request
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/4"
    actions:
      - type: gate
        left: "%payload.pull_request.head.ref%"
        operator: "==="
        right: add-education
        else:
          type: respond
          with: e_error.md
      - type: getPullRequest
        waitForMergeable: true
        action_id: pr
      - type: gate
        left: "%actions.pr.data.mergeable%"
        else:
          type: respond
          with: e_error.md
      - type: getPullRequest
        pullRequest: Another User's Change
        action_id: new_pr
      - type: respond
        with: 05_first-commit-success.md
        data:
          secondPR: "%actions.new_pr.data.html_url%"
      - type: removeBranchProtection
      - type: mergePullRequest
        pullRequest: Another User's Change
      - type: updateBranchProtection

  #step 6: resolve created conflict
  - title: Resolve conflicts created
    description: Resolve the conflict in the 'Create Your Own Conflict' pull request
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/4"
    actions:
      - type: gate
        left: "%payload.pull_request.head.ref%"
        operator: "==="
        right: add-education
        else:
          type: respond
          with: e_error.md
      - type: getPullRequest
        waitForMergeable: true
        action_id: pr
      - type: gate
        left: "%actions.pr.data.mergeable%"
        else:
          type: respond
          with: e_error.md
      - type: respond
        with: 06_PR-free-of-conflicts.md
        data:
          branch: "%payload.pull_request.head.ref%"
      - type: removeBranchProtection

  #step 7: merge
  - title: Merge the third pull request
    description: Merge the 'Create Your Own Conflict' pull request
    event: pull_request.closed
    link: "{{ repoUrl }}/pull/4"
    actions:
      - type: gate
        left: "%payload.pull_request.head.ref%"
        operator: "==="
        right: add-education
        else:
          type: respond
          with: e_error.md
      - type: gate
        left: "%payload.pull_request.merged%"
      - type: respond
        with: 07_congrats.md
        data:
          url: "%actions.issue.data.html_url%"
